Repository GustavodeJesus/mentoria-java, pull requests merged in 2025-06, with the labels that each got.

#76 task: configurado formulario para cadastro de clientes.
  src/main/java/br/com/mentoriajava/clientes/ClientesScreen.java
Labels: Task

#82 task: Pop-up confirmando cadastro de produto
  src/main/java/br/com/mentoriajava/produtos/ProdutosScreen.java
Labels: Task

#80 Task: Criado listagem de vendedores
  src/main/java/br/com/mentoriajava/database/VendedorDataSource.java
  src/main/java/br/com/mentoriajava/home/HomeApp.java
  src/main/java/br/com/mentoriajava/vendedores/ListagemVendedoresScreen.java
  src/main/java/br/com/mentoriajava/vendedores/VendedoresScreen.java
Labels: Task

#66 Chore/correcao classe cupom
  .github/pull_request_template.md
  .gitignore
  .mvn/wrapper/MavenWrapperDownloader.java
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  README.md
  docs/edit_configurations.png
  docs/edit_vm_options.png
  mvnw.cmd
  pom.xml
  scripts/install-openjfx.ps1
  src/main/java/br/com/mentoriajava/PedidoApp.java
  src/main/java/br/com/mentoriajava/base/Endereco.java
  src/main/java/br/com/mentoriajava/base/Pessoa.java
  src/main/java/br/com/mentoriajava/base/ValidaCPF.java
  src/main/java/br/com/mentoriajava/base/ValidarCamposObrigatorios.java
  src/main/java/br/com/mentoriajava/clientes/Cliente.java
  src/main/java/br/com/mentoriajava/clientes/ClientesScreen.java
  src/main/java/br/com/mentoriajava/clientes/StatusCivilEnum.java
  src/main/java/br/com/mentoriajava/cupons/Cupom.java
  src/main/java/br/com/mentoriajava/cupons/CupomDeDesconto.java
  src/main/java/br/com/mentoriajava/cupons/CuponsEnum.java
  src/main/java/br/com/mentoriajava/cupons/CuponsScreen.java
  src/main/java/br/com/mentoriajava/database/CupomDataSource.java
  src/main/java/br/com/mentoriajava/database/PetDataSource.java
  src/main/java/br/com/mentoriajava/exemplo/Pet.java
  src/main/java/br/com/mentoriajava/exemplo/PetScreen.java
  src/main/java/br/com/mentoriajava/formaspagamento/FormaDePagamento.java
  src/main/java/br/com/mentoriajava/formaspagamento/FormaPagamentoScreen.java
  src/main/java/br/com/mentoriajava/formaspagamento/TiposDePagamentos.java
  src/main/java/br/com/mentoriajava/home/HomeApp.java
  src/main/java/br/com/mentoriajava/pedido/Entrega.java
  src/main/java/br/com/mentoriajava/pedido/PedidosScreen.java
  src/main/java/br/com/mentoriajava/produtos/ProdutosScreen.java
  src/main/java/br/com/mentoriajava/vendedores/Vendedor.java
  src/main/java/br/com/mentoriajava/vendedores/VendedoresScreen.java
  src/main/resources/icons/clientes.png
  src/main/resources/icons/cupons.png
  src/main/resources/icons/formapagamento.png
  src/main/resources/icons/info.png
  src/main/resources/icons/lixeira.png
  src/main/resources/icons/pedidos.png
  src/main/resources/icons/produtos.png
  src/main/resources/icons/vendedores.png
Labels: Blocked

#65 task: criado cupomDataSource
  src/main/java/br/com/mentoriajava/cupons/Cupom.java
  src/main/java/br/com/mentoriajava/cupons/CuponsEnum.java
  src/main/java/br/com/mentoriajava/database/CupomDataSource.java
Labels: Task

#85 feature: criar tela cadastro vendedores
  src/main/java/br/com/mentoriajava/database/VendedorDataSource.java
  src/main/java/br/com/mentoriajava/home/HomeApp.java
  src/main/java/br/com/mentoriajava/vendedores/ListagemVendedoresScreen.java
  src/main/java/br/com/mentoriajava/vendedores/StatusVendedorEnum.java
  src/main/java/br/com/mentoriajava/vendedores/Vendedor.java
  src/main/java/br/com/mentoriajava/vendedores/VendedoresScreen.java
Labels: Feature

#83 feature: criar tela cadastro produtos
  src/main/java/br/com/mentoriajava/database/ProdutoDataSource.java
  src/main/java/br/com/mentoriajava/produtos/Produto.java
  src/main/java/br/com/mentoriajava/produtos/ProdutoCategoria.java
  src/main/java/br/com/mentoriajava/produtos/ProdutosScreen.java
Labels: Feature

#77 task: criar tabela listagem cliente
  br/com/mentoria/java/Main.java
  src/main/java/br/com/mentoriajava/PedidoApp.java
Labels: Task

#86 task: criar popup confirmacao cadastro
  br/com/mentoria/java/Main.java
  src/main/java/br/com/mentoriajava/clientes/ClientesScreen.java
Labels: Task

#87 feature: criar tela cadastro cliente
  src/main/java/br/com/mentoriajava/PedidoApp.java
  src/main/java/br/com/mentoriajava/clientes/Cliente.java
  src/main/java/br/com/mentoriajava/clientes/ClientesScreen.java
  src/main/java/br/com/mentoriajava/database/ClienteDataSource.java
Labels: Feature

#88 chore: alteração do titulo da tela de produtos
  src/main/java/br/com/mentoriajava/produtos/ProdutosScreen.java
Labels: Chore
